### ISSUE TITLE
Hangfire.io homepage "Easy to set up, easy to use" link broken

### ISSUE THREAD

**Issue by pwhe23** [HangfireIO/HangfireIO.github.io#13]
Under "Simple":
"Easy to set up, easy to use". No Windows Service, no Windows Scheduler, no separate applications required.

Link should be "http://docs.hangfire.io/en/latest/quick-start.html". Note the dash in "quick-start.html"

**Comment by odinserj** [comment]
Thanks, Paul, fixed!
